"""Add nationality to players

Revision ID: 68e72bd22c8f
Revises: 7dabe222056c
Create Date: 2026-03-21 19:45:45.630496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e72bd22c8f'
down_revision: Union[str, None] = '7dabe222056c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('nationality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'nationality')
    # ### end Alembic commands ###
